name: Build dbpf_unpacker (Windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-native-image:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add GraalVM to PATH
        run: |
          echo "${{ env.GRAALVM_HOME }}\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
        shell: pwsh

      - name: Install Native Image
        run: |
          & "${{ env.GRAALVM_HOME }}\bin\gu" install native-image
        shell: pwsh

      - name: Compile Java Source Files
        run: |
          mkdir build
          javac -deprecation -Werror -d build -sourcepath src src/sporemodder/*.java

      - name: Create JAR File
        run: |
          mkdir bin
          jar -cfm bin/dbpf_unpacker.jar src/sporemodder/Manifest.mf -C build .

      - name: Create Native Binary
        run: |
          native-image -jar bin/dbpf_unpacker.jar -H:Name=dbpf_unpacker -H:Class=sporemodder.Main -H:NativeLinkerOption="${{ github.workspace }}/res/dbpf_unpacker.res"

      - name: Upload Native Binary
        uses: actions/upload-artifact@v3
        with:
          name: dbpf_unpacker-windows-x64
          path: ./bin/dbpf_unpacker.exe

      - name: Upload Registry Files
        uses: actions/upload-artifact@v3
        with:
          name: dbpf_unpacker-registry-files
          path: ./*.txt
