name: Build dbpf_unpacker (Ubuntu)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-native-image:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Native Image
        run: gu install native-image

      - name: Compile Java Source Files
        run: |
          mkdir build
          javac -deprecation -Werror -d build -sourcepath src  src/sporemodder/*.java

      - name: Create JAR File
        run: |
          mkdir bin
          jar -cfm bin/dbpf_unpacker.jar  src/sporemodder/Manifest.mf  -C build  .

      - name: Create Native Binary
        run: |
          native-image \
            -jar bin/dbpf_unpacker.jar \
            -H:Name=dbpf_unpacker \
            -H:Class=sporemodder.Main

      - name: Upload Native Binary
        uses: actions/upload-artifact@v3
        with:
          name: dbpf_unpacker-ubuntu-x64
          path: ./dbpf_unpacker
          
      - name: Upload Registry Files
        uses: actions/upload-artifact@v3
        with:
          name: dbpf_unpacker-registry-files
          path: ./*.txt
